config/routes.rb
Tapestry::Application.routes.draw do
  root :to => 'pages#show', :id => 'home'

  match '/study_guide_pages/:exam_id/:ordinal' => 'study_guide_pages#show', :as => :show_study_guide_page
  match '/study_guide_pages/:exam_id' => 'study_guide_pages#index', :as => :study_guide_page

  resources :google_spreadsheets

  resources :withdrawal_comments
  resources :permissions
  get 'permissions/update_subject_select'
  get 'permissions/update_subject_select/:subject_class' => 'permissions#update_subject_select'
  get 'permissions/update_subject_select/:subject_class/:id' => 'permissions#update_subject_select'

  resources :plates
  match '/plates/m/:url_code' => 'plates#mobile', :as => :mobile_plate, :via => :get
  match '/plates/:plate_id/assign/:plate_layout_position_id/:sample_id' => 'plates#mobile_assign_position', :as => :mobile_assign_plate_position, :via => :post
  match '/plates/:plate_id/destroy/:plate_layout_position_id' => 'plates#mobile_destroy_position', :as => :mobile_destroy_plate_position, :via => :post
  match '/plates/select_layout_mask/:url_code/:plate_layout_mask_id' => 'plates#mobile_select_layout_mask', :as => :mobile_select_plate_layout_mask, :via => :post
  match '/plates/mobile_stop/:id' => 'plates#mobile_stop', :as => :mobile_stop_plate, :via => :post
  match '/plates/:plate_id/destroy_sample/:plate_layout_position_id' => 'plates#destroy_sample', :as => :destroy_plate_sample, :via => :post
  match '/plates/:id/dup' => 'plates#dup', :as => :dup_plate, :via => :post

  get 'sample_show' => 'samples#show'
  get 'sample_log'  => 'samples#show_log'
  get 'sample_edit' => 'samples#edit'
  post 'sample_receive_by_crc_id' => 'samples#receive_by_crc_id'
  match '/samples/receive' => 'samples#receive', :as => :receive_sample
  match '/samples/receive_multiple/:url_codes' => 'samples#receive_multiple', :as => :receive_multiple_samples
  match '/samples/receive_multiple_confirm' => 'samples#receive_multiple_confirm', :as => :receive_multiple_samples_confirm, :via => :post
  match '/samples/:id/log' => 'samples#show_log', :as => :show_sample_log, :via => :get
  match '/samples/:id/participant_note' => 'samples#participant_note', :as => :sample_participant_note, :via => :get
  match '/samples/:id/participant_note' => 'samples#update_participant_note', :as => :sample_update_participant_note, :via => :put
  match '/samples/:id/destroyed' => 'samples#mark_as_destroyed', :as => :sample_destroyed, :via => :post
  resources :samples
  match '/samples/:id/received' => 'samples#received', :as => :received_sample, :via => :post
  match '/samples/m/:url_code/undo_reception' => 'samples#mobile_undo_reception', :as => :mobile_sample_undo_reception, :via => :get
  match '/samples/m/:url_code/receive' => 'samples#mobile_receive', :as => :mobile_sample_receive, :via => :get
  match '/samples/m/:url_code' => 'samples#mobile', :as => :mobile_sample, :via => :get
  resources :specimens, :controller => "samples"

  resources :unused_kit_names

  match '/kits/:id/log' => 'kits#show_log', :as => :show_kit_log, :via => :get
  match '/kits/:id/confirm_claim' => 'kits#confirm_claim', :as => :kit_confirm_claim, :via => :post
  match '/kits/claim' => 'kits#claim', :as => :kit_claim

  match '/admin/researchers/study_filter_results' => 'admin/researchers#study_filter_results', :format => 'csv', :as => :study_filter_results_csv

  resources :kits
  match '/kits/:id/sent' => 'kits#sent', :as => :sent_kit, :via => :post
  match '/kits/:id/returned' => 'kits#returned', :as => :returned_kit, :via => :post
  match '/kits/sent_selected' => 'kits#sent_selected', :as => :sent_selected_kits, :via => :post
  match '/kits/:id/lost' => 'kits#lost', :as => :lost_kit, :via => :post

  resources :traitwise_surveys do
    post 'participate', :on => :member
    post 'synchronize', :on => :member
    post 'download', :on => :member
  end
  match '/traitwise/proxy' => 'traitwise#proxy'
  match '/traitwise/:id' => 'traitwise#index', :as => :take_traitwise_survey
  match '/traitwise/:id/iframe' => 'traitwise#iframe', :as => :traitwise_iframe

  resources :google_surveys do
    post 'participate', :on => :member
    # So that going via login_required when clicking on the link in a reminder e-mail doesn't break the flow,
    # we also support the GET method.
    get 'participate', :on => :member
    post 'synchronize', :on => :member
    post 'send_test_reminder', :on => :member
    match 'download', :on => :member
    match 'download_bypasses', :on => :member
  end
  match '/nonce/:id' => 'nonces#delete', :as => :delete_google_survey_answers, :via => :delete
  match '/google_survey_reminder/edit' => 'google_survey_reminders#edit', :as => :edit_google_survey_reminder
  match '/google_survey_reminder/update' => 'google_survey_reminders#update', :as => :update_google_survey_reminder, :via => :post
  # So that going via login_required when clicking on the link in a reminder e-mail doesn't break the flow,
  # we also support the GET method.
  match '/google_survey_bypass/:token' => 'google_survey_bypasses#record', :as => :google_survey_bypass, :via => [:get, :post]

  resources :google_spreadsheets do
    post 'synchronize', :on => :member
  end

  get "oauth_tokens/authorize"
  get "oauth_tokens/revoke"
  match "oauth_tokens/get_access_token" => 'oauth_tokens#get_access_token', :as => :get_oauth_access_token, :via => :get
  get 'oauth2callback' => 'oauth_tokens#oauth2callback', :as => :oauth2callback
  resources :oauth_tokens, :only => :index

  resources :kit_design_samples
  get 'sample_type_show' => 'sample_types#show'
  resources :sample_types
  resources :units
  resources :device_types
  resources :tissue_types
  resources :kit_designs
  match '/collection_events/claim' => 'studies#claim', :as => :study_claim_kit
  match '/collection_events/:id/users' => 'studies#users', :as => :study_users
  match '/collection_events/:id/sent_kits_to_selected' => 'studies#sent_kits_to_selected', :as => :sent_kits_to_selected_study_users
  match '/collection_events/:id/map' => 'studies#map', :as => :study_map
  match '/collection_events/:study_id/users/:user_id/:status' => 'studies#update_user_status', :as => :study_update_user_status
  match '/collection_events/:id/sent_kits_to_selected' => 'studies#sent_kits_to_selected', :as => :sent_kits_to_selected_study_users, :via => :post
  match '/collection_events/:id/accept_interested_selected' => 'studies#accept_interested_selected', :as => :accept_interested_selected_study_users, :via => :post
  resources :collection_events, :controller => "studies"
  match '/pages/studies', :to => redirect('/pages/collection_events')
  match '/studies/*x', :to => redirect('/collection_events/%{x}')

  get 'third_party/index'
  get 'third_party/study/:id' => 'studies#show_third_party', :as => :third_party_study
  match '/third_party/study/:id/verify_participant_id/:app_token' => 'studies#verify_participant_id', :via => [:get], :as => :verify_third_party_participant_id
  match '/third_party/study/:id/clickthrough_to' => 'studies#clickthrough_to', :via => [:post], :as => :clickthrough_to_third_party
  post '/third_party/add_dataset' => 'studies#add_dataset'
  match '/3p/*x', :to => redirect('/third_party/%{x}')

  get 'open_humans/participate'
  post 'open_humans/disconnect'
  post 'open_humans/tokens', :to => 'open_humans#create_token'
  post 'open_humans/huids', :to => 'open_humans#create_huid'
  get 'open_humans/huids'
  # This callback URL is set on the Open Humans API server
  get 'auth/open-humans/callback' => 'open_humans#callback'

  match '/filters/upload' => 'filters#upload', :as => :upload_filter, :via => :post

  resources :pages
  match '/23andme' => 'pages#show', :id => '23andme', :as => 'twenty3andme'
  match '/23andMe' => 'pages#show', :id => '23andme', :as => 'twenty3andme'
  match '/enrolled', :to => redirect('/users')
  match '/users/initial' => 'users#initial', :as => :initial_user
  match '/users/create_initial' => 'users#create_initial', :as => :create_initial_user
  match '/users/new2' => 'users#new2', :as => :new2_user
  match '/users/accept_enrollment' => 'users#accept_enrollment', :as => :accept_enrollment_user
  match '/users/tos' => 'users#tos', :as => :tos_user
  match '/users/accept_tos' => 'users#accept_tos', :as => :accept_tos_user
  match '/users/consent' => 'users#consent', :as => :consent_user
  match '/users/unauthorized' => 'users#unauthorized', :as => :unauthorized_user
  match '/users/deactivated' => 'users#deactivated', :as => :deactivated_user
  match '/users/created/:id' => 'users#created', :as => :created_user
  match '/users/show_log' => 'users#show_log', :as => :show_log_user
  match '/users/withdraw' => 'users#withdraw', :as => :withdraw_user, :via => :post
  match '/users/withdraw_confirm' => 'users#withdraw_confirm', :as => :withdraw_confirm_user, :via => :post
  match '/users/:switch_to_id/switch_to' => 'users#switch_to', :via => [:post], :as => :switch_to_user
  match '/drb/userlog/:user_id' => 'drb#userlog', :as => :userlog_drb
  match '/user/study/:study_id' => 'users#edit_study', :as => :user_edit_study, :via => :get
  match '/user/study/:study_id' => 'users#update_study', :as => :user_update_study, :via => :post
  match '/users/resend_signup_notification_form' => 'users#resend_signup_notification_form', :as => :resend_signup_notification_form
  match '/users/resend_signup_notification/:id' => 'users#resend_signup_notification', :as => :resend_signup_notification_user
  match '/users/create_researcher', :as => :create_researcher, :via => :post
  match '/users/participant_survey' => 'users#participant_survey'
  resources :shipping_addresses
  match '/user/shipping_address' => 'users#shipping_address', :as => 'user_shipping_address'
  match '/user/edit' => 'users#edit', :as => 'edit_user', :method => :get
  match '/user/update' => 'users#update', :as => 'update_user', :method => :post
  resources :users

  resource :session
  match '/login' => 'sessions#new', :as => :login

app/models/sample_type.rb
class SampleType < ActiveRecord::Base
  stampable
  acts_as_paranoid_versioned :version_column => :lock_version

  validates_presence_of    :name
  validates_uniqueness_of  :name

  validates_presence_of    :description
  validates_presence_of    :target_amount

  validates_presence_of    :tissue_type_id
  validates_presence_of    :device_type_id
  validates_presence_of    :unit_id

  belongs_to :tissue_type
  belongs_to :device_type
  belongs_to :unit
end

app/views/samples/edit.html.erb
<h2>Edit sample <%= "#{@sample.crc_id_s} (#{@sample.name})" %></h2>

<%= render 'form' %>

app/views/samples/index.html.erb
<h2>Specimens</h2>

<% content_for :js do %>
jQuery(function() {
    var $ = jQuery.noConflict();
    $(document).ready(function() {
        $("noscript").remove();
        $("#samples").removeClass('admin_table');
        $('#samples').dataTable( {
            "oSearch": { "sSearch": <%= raw (params[:q] || '').to_json %> },
<% if bootstrap? && false %>
            "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
<% end %>
            "bProcessing": true,
            "bServerSide": true,
            "bJQueryUI": true,
            "sAjaxSource": '<%=j(samples_path(:include_derived_samples => params[:include_derived_samples]))%>',
            "aoColumns": [
                { 'mDataProp': 'crc_id',
                  'fnRender': function(oObj) {
                      var r = '' + oObj.aData.crc_id;
                      if(oObj.aData.id)
                          r = '<a href="<%= sample_show_path %>?id=' + oObj.aData.id + '">' + r + '</a>';
                      if (oObj.aData.url_code)
                          r += ' (' + oObj.aData.url_code + ')';
                      return r;
                  }
                },
                { 'mDataProp': 'material',
                        'fnRender': function(oObj) {
                        var s='';
                        if (oObj.aData.material) {
                            s += oObj.aData.material;
                            if (oObj.aData.amount && oObj.aData.unit)
                                s += ', ' + oObj.aData.amount + ' ' + oObj.aData.unit;
                        }
                        return s;
                    }
                },
                { 'mDataProp': 'study.name' },
                { 'mDataProp': 'kit.name',
                  'bVisible': <%= (current_user) ? 'true' : 'false' %>
                },
                { 'mDataProp': 'participant.hex',
                  'fnRender': function(oObj) {
                      if (!oObj.aData.participant ||
                          !oObj.aData.participant.hex)
                          return '';
                      return '<a href="<%= profile_public_path %>?hex=' + oObj.aData.participant.hex + '">' + oObj.aData.participant.hex + '</a>';
                  }
                },
                { 'mDataProp': 'qc_result.QC Status',
                  'bVisible': <%= (current_user and current_user.is_admin?) ? 'true' : 'false' %>,
                  'asSorting': ['desc','asc']
                },
                { 'mDataProp': 'owner.display_name',
                  'bSortable': false,
                  'fnRender': function(oObj) {
                      if (!oObj.aData.owner)
                          return '';
                      if (oObj.aData.owner.hex)
			                    return '<a href="<%= profile_public_path %>?hex=' + oObj.aData.owner.hex + '">' + oObj.aData.owner.hex + '</a>';
                      if (oObj.aData.owner.researcher_affiliation)
                          return oObj.aData.owner.researcher_affiliation;
                      else
                          return oObj.aData.owner.full_name;
                  }
                },
                { 'mDataProp': 'log_url',
                  'bVisible': <%= (current_user and current_user.is_admin?) ? 'true' : 'false' %>,
                  'bSortable': false,
                  'fnRender': function(oObj) {
                      if(!oObj.aData.id)
                          return null;
                      return '&nbsp;<a href="<%= sample_log_path %>?id='+oObj.aData.id+'">log</a>&nbsp;';
                  } },
                { 'mDataProp': 'edit_url',
                  'bVisible': <%= (current_user and current_user.is_admin?) ? 'true' : 'false' %>,
                  'bSortable': false,
                  'fnRender': function(oObj) {
                      if(!oObj.aData.id)
                          return null;
                      return '&nbsp;<a href="<%= sample_edit_path %>?id=' + oObj.aData.id + '">edit</a>&nbsp;';
                  } },
                { 'mDataProp': 'delete_url',
                  'bVisible': <%= (false and current_user and current_user.is_admin?) ? 'true' : 'false' %>,
                  'bSortable': false,
                  'fnRender': function(oObj) {
                      if(!oObj.aData.id || oObj.aData.last_mailed)
                          return null;
                      return '&nbsp;<a href="samples/'+oObj.aData.id+'/delete">delete</a>&nbsp;';
                  } } ]
            } ).
            fnSetFilteringDelay().
            fnSkipMissingDataProps();
    } );
});
<% end %>
<% content_for :head do %>
  <%= javascript_include_tag 'jquery.dataTables.fnSetFilteringDelay' %>
  <%= javascript_include_tag 'jquery.dataTables.fnSkipMissingDataProps' %>
  <%= javascript_include_tag 'jquery.dataTables.renderers' %>
<% end %>

<p>
<% if current_user and current_user.is_admin? %>
Because you are an administrator, this page lists all samples (specimen containers) that have been created by any researcher, even unclaimed/unused ones.
<% elsif current_user and current_user.is_researcher? %>
This page lists all samples (specimen containers) created for your collection events, and all specimens that have been collected from participants.
<% elsif current_user %>
This page lists all specimen containers claimed by you, and all specimens that have been collected from participants.
<% else %>
This page lists all specimens that have been collected from participants.
<% end %>
</p>

<p>
The "Search" box may be used to search on any field; e.g., "blood", "Coriell", "hu43860C".
</p>

<% if current_user and current_user.is_researcher? %>
<p>
  <%= link_to 'Enter IDs of received samples here', receive_sample_path %>
  when you receive samples from a participant or researcher.
</p>
<% end %>

<noscript><%= will_paginate @samples %></noscript>
<table id="samples" style="width: 100%" class="admin_table">
  <thead>
    <tr>
      <th width="10%">Number</th>
      <th width="10%">Material</th>
      <th width="35%">Collection event</th>
      <th width="8%">Kit</th>
      <th width="7%">Participant</th>
      <th width="8%">QC</th>
      <th width="12%">Location</th>
      <th width="5%">&nbsp;</th>
      <th width="5%">&nbsp;</th>
      <th width="5%">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <noscript>
      <% @samples.each do |sample| %>
      <tr>
	<td><%= link_to sample.crc_id_s, sample %></td>
	<td><%= sample.study.name %></td>
	<td><%= sample.kit.name if sample.kit %></td>
	<td><%= sample.participant.nil? ? '' : link_to(sample.participant.hex, public_profile_path(sample.participant.hex)) %></td>
	<td>
	  <% if sample.owner.nil? %>
	  <% elsif sample.owner.is_researcher? %>
	  <%= sample.owner.full_name %>
	  <% else %>
	  <%= sample.owner.hex %>
	  <% end %>
	</td>
        <td><%= sample.qc_result ? 'Y' : '' %></td>
	<td><%= link_to 'Log', show_sample_log_path(sample), :class => "iframe", :title => "Sample log for #{sample.name} (#{sample.kit ? sample.kit.name : 'no'} kit)" %></td>
	<td><%= link_to 'Edit', edit_sample_path(sample) %></td>
	<td><%= sample.last_mailed.nil? ? link_to('Delete', sample, :confirm => 'Are you sure?', :method => :delete) : '' %></td>
      </tr>
      <% end %>
    </noscript>
  </tbody>
</table>
<noscript><%= will_paginate @samples %></noscript>

app/views/samples/mobile.html.erb
<html>
<head>
  <%= stylesheet_link_tag 'none', :media => 'screen' %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag %w(scan_button) %>
</head>
<body>

<div align="center" width="100%">
  <% flash.each do |key, value| -%>
    <div class="flash <%= raw(alert_classes_for_flash_key(key)) %>">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= raw(flash.delete key) %>
    </div>
  <% end -%>
  <% flash = {} -%>
</div>

<p align="center"><font size="+9"><strong><%= @sample.crc_id %></strong></font><br/><font size="+3"><%= @sample.name %></font></p>

<font size="+9">
<% if @sample.owner == current_user then %>
<p align="center"><font color="darkgreen"><strong>RECEIVED</strong></font></p>

<p align="center"><font color="red"><%= link_to('UNMARK AS RECEIVED', mobile_sample_undo_reception_path(@sample.url_code)) %></font></p>

<% else %>
<p align="center"><font color="darkred"><strong>NOT RECEIVED</strong></font></p>

<p align="center"><font color="green"><%= link_to('MARK AS RECEIVED', mobile_sample_receive_path(@sample.url_code), :method => :get) %></font></p>

<% end %>

<div style="width:60%; margin:0 auto"><%= button_to "Resume #{session[:scan_context_gerund]}", session[:scan_context_path], :method => :get, :style => "width:100%; padding:1em 2em; white-space:normal" if @have_scan_context %></div>

<div style="width:60%; margin:0 auto"><%= button_to "Scan another", "http://zxing.appspot.com/scan", :method => :get, :class => "launch_scanner", :style => "width:100%; padding:1em 2em; white-space:normal" %></div>

</font>

</body>
</html>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/receive.html.erb
<h2><%= link_to 'Samples', samples_path %> &rarr; receive</h2>

<% content_for :js do %>
jQuery(function(){
        var $ = jQuery.noConflict();
        $('form.receive-sample').bind('submit', function(){
                var thisform = this;
		var $crc_input = $('input[name=crc_id]',this);
                var crc_id = $crc_input.val();
                $('.response', thisform).html('[loading]');
                $.ajax( { 'dataType': 'json',
                            'type': 'POST',
                            'url': '<%= sample_receive_by_crc_id_path %>?crc_id=' + crc_id,
                            'success': function(d,t,r) {
                            $('.response', thisform).html(crc_id + (d.ok ? ': ' : ': Error: ') + d.message);
                            if (d.redirect_to) {
                                $('.response', thisform).html(d.message);
                                window.location.href = d.redirect_to;
                            }
			    else if (d.ok)
				$crc_input.attr('value', '');
			    $crc_input.focus();
                        }
                    } );
                return false;
            });
        $('input[name=crc_id]',this).focus();
    });
<% end %>

<p>When you receive a sample from a participant or another researcher, enter the sample ID number or alphanumeric code here.</p>

<form action="#" class="receive-sample">
<input type="text" name="crc_id" isindex />
<input type="submit" value="I have received this sample / kit" />
<br />
<br />
<span class="response">&nbsp;</span>
</form>

<p>If you are receiving many samples at once, note:</p>
<ul>
  <li>You can enter multiple IDs.  Separate them with commas or spaces.</li>
  <li>You can enter kit IDs and kit names.</li>
  <li>If you enter a kit ID, or multiple sample IDs, you will confirm the individual sample IDs on the next page.  (If you enter just one sample ID, we will just process it right away.)</li>
</ul>

<% if current_user.is_admin? # (not hardened yet; see FiltersController) %>

<p>You can also upload a CSV file containing <em>one sample bar code per row</em> (and optionally a plate ID like "1234567890" and well ID like "A01")<br />
<%= form_for :upload, :url => upload_filter_path, :html => { :multipart => true } do |f| %>
<%= hidden_field_tag :target_class, 'Sample' %>
<%= hidden_field_tag :target_id_attribute, 'url_code' %>
<%= hidden_field_tag :return_to, receive_multiple_samples_path('FILE') %>
<%= file_field_tag 'file' %><br />
<%= f.submit 'Upload CSV of sample bar codes' %>
<% end %>

<% end %>

app/views/samples/receive_multiple.html.erb
<h2><%= link_to 'Samples', samples_path %> &rarr; <%= link_to 'receive', receive_sample_path %> &rarr; multiple samples</h2>

<% content_for :head do %>
    <style type="text/css">
    table#which-samples tbody tr td {
        vertical-align: middle;
    }
    table#which-samples tbody tr.checkable:hover {
	background: #c7d1e7;
    }
    </style>
<% end %>
<% content_for :js do %>
jQuery(function(){
    var $ = jQuery.noConflict();
    $(document).
	delegate('table#which-samples tbody tr.checkable', 'click', {},
		 function(event, ui) {
                     if ($(event.srcElement).is('input,button,a'))
                         return true;
		     var i = $(this).find('input[type=checkbox]');
		     i.attr('checked', !i[0].checked);
		 });
    $(document).
	delegate('button.selectall,button.deselectall', 'click', {},
		 function(event, ui) {
		     $('table#which-samples tr.checkable input[type=checkbox]').
			 attr('checked', $(event.srcElement).hasClass('selectall'));
		 });
    });
<% end %>

<p>
  <b>Please indicate which samples you received.</b>  Compare the
  following sample codes with the labels on the samples themselves.
  Tick the checkboxes for the samples you have in front of you.
  Then click the "Receive" button below.
</p>

<p>
  <button class="selectall">Select all</button>
  <button class="deselectall">Deselect all</button>
</p>

<% rownumber = 0 %>
<%= form_for(:sample, :url => receive_multiple_samples_confirm_path, :method => :post) do |f| %>
<%= hidden_field_tag :selection_id, @selection.id if @selection %>
<div class="profile-data">

  <table id="which-samples">
    <thead>
      <tr>
	<th style="text-align:center">Received?</th>
	<th>Kit name / sample code</th>
	<th>Sample name / device</th>
	<th>Participant</th>
	<th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @samples.each do |sample| %>
      <% row_is_checkable = (sample.owner != current_user || (@sample_info[sample.id] && @sample_info[sample.id][:plate])) %>
      <tr class="<%= "checkable" if row_is_checkable %>">
	<td style="text-align:center"><%= check_box 'confirm_url_codes', sample.url_code, :checked => !!@default_checked_hack[sample.url_code] if row_is_checkable %></td>
	<td>
	  <% if sample.kit %>
	  <%= sample.kit.name %> &mdash;
	  <% end %>
	  <code><b><%= sample.url_code %></b></code>
	</td>
	<td>
	  <%= sample.name %>
	  <% if sample.original_kit_design_sample %>
	  <br />
	  <%= sample.original_kit_design_sample.device %>
	  <% end %>
	</td>
	<td>
	  <% if sample.participant %>
	  <%= @reveal_participant ? link_to(sample.participant.hex, public_profile_path(sample.participant.hex)) : "Yes" %>
	  <% else %>
	  <b>Unknown!</b>
	  <% end %>
	</td>
	<td>
	  <% if sample.owner != current_user %>
	  Receive
	  <% if (sample.participant && (!sample.owner || sample.owner == sample.participant)) %>
	  from participant <%= sample.participant.hex if sample.participant.is_enrolled? %>
	  <% elsif sample.owner and sample.owner.researcher %>
	  from 
	  <%= sample.owner.full_name %>,
	  <%= sample.owner.researcher_affiliation %>
	  <% end %>
	  <br />
	  <% end %>
	  <% if @selection and @sample_info[sample.id] and @sample_info[sample.id][:plate] %>
	  &rarr; <%= @sample_info[sample.id][:plate_layout_position].name %>
	  on
	  <%= link_to @sample_info[sample.id][:plate].crc_id_s, @sample_info[sample.id][:plate] %>
	  (<%= @sample_info[sample.id][:plate].description %>)
	  <% if @sample_info[sample.id][:position_collision] %>
	  <br />
	  <span style="background:#f88; padding: 1px 1em">
	    Replacing sample <%= link_to @sample_info[sample.id][:position_collision].sample.crc_id_s, @sample_info[sample.id][:position_collision].sample %>
	  </span>
	  <% end %>
	  <% elsif sample.owner == current_user %>
	  <span style="color: #888">(already received; nothing to do)</span>
	  <% end %>
	</td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br clear="all" />
  <span style="margin: 1em auto; padding: 1em; background: #c7d1e7">
    <%= f.submit "Receive" %>
  </span>
</div>

<% end %>

<% if @selection and (nfk = @selection.notfound_keys) and !nfk.empty? %>
<div style="clear:both; border:1px dashed #800;padding:.5em 1em;margin-top:2em">
  <p>
    <%= nfk.size %> of the provided sample IDs <%= nfk.size==1 ? 'was' : 'were' %> not found.
    <ul>
      <% i=-1; nfk.each do |k| %>
      <% if (i += 1) == 32 and nfk.size > 64 %>
      <li><b>[and <%= nfk.size-32 %> more, not shown]</b></li>
      <% break %>
      <% end %>
      <li>
        <% if k %>
        &ldquo;<%= k %>&rdquo;
        <% else %>
        nil
        <% end %>
      </li>
      <% end %>
    </ul>
  </p>
</div>
        
<% end %>