config/routes.rb
Tapestry::Application.routes.draw do
  root :to => 'pages#show', :id => 'home'

  match '/study_guide_pages/:exam_id/:ordinal' => 'study_guide_pages#show', :as => :show_study_guide_page
  match '/study_guide_pages/:exam_id' => 'study_guide_pages#index', :as => :study_guide_page

  resources :google_spreadsheets

  resources :withdrawal_comments
  resources :permissions
  get 'permissions/update_subject_select'
  get 'permissions/update_subject_select/:subject_class' => 'permissions#update_subject_select'
  get 'permissions/update_subject_select/:subject_class/:id' => 'permissions#update_subject_select'

  resources :plates
  match '/plates/m/:url_code' => 'plates#mobile', :as => :mobile_plate, :via => :get
  match '/plates/:plate_id/assign/:plate_layout_position_id/:sample_id' => 'plates#mobile_assign_position', :as => :mobile_assign_plate_position, :via => :post
  match '/plates/:plate_id/destroy/:plate_layout_position_id' => 'plates#mobile_destroy_position', :as => :mobile_destroy_plate_position, :via => :post
  match '/plates/select_layout_mask/:url_code/:plate_layout_mask_id' => 'plates#mobile_select_layout_mask', :as => :mobile_select_plate_layout_mask, :via => :post
  match '/plates/mobile_stop/:id' => 'plates#mobile_stop', :as => :mobile_stop_plate, :via => :post
  match '/plates/:plate_id/destroy_sample/:plate_layout_position_id' => 'plates#destroy_sample', :as => :destroy_plate_sample, :via => :post
  match '/plates/:id/dup' => 'plates#dup', :as => :dup_plate, :via => :post

  get 'sample_show' => 'samples#show'
  get 'sample_log'  => 'samples#show_log'
  get 'sample_edit' => 'samples#edit'
  post 'sample_receive_by_crc_id' => 'samples#receive_by_crc_id'
  match '/samples/receive' => 'samples#receive', :as => :receive_sample
  match '/samples/receive_multiple/:url_codes' => 'samples#receive_multiple', :as => :receive_multiple_samples
  match '/samples/receive_multiple_confirm' => 'samples#receive_multiple_confirm', :as => :receive_multiple_samples_confirm, :via => :post
  match '/samples/:id/log' => 'samples#show_log', :as => :show_sample_log, :via => :get
  match '/samples/:id/participant_note' => 'samples#participant_note', :as => :sample_participant_note, :via => :get
  match '/samples/:id/participant_note' => 'samples#update_participant_note', :as => :sample_update_participant_note, :via => :put
  match '/samples/:id/destroyed' => 'samples#mark_as_destroyed', :as => :sample_destroyed, :via => :post
  resources :samples
  match '/samples/:id/received' => 'samples#received', :as => :received_sample, :via => :post
  match '/samples/m/:url_code/undo_reception' => 'samples#mobile_undo_reception', :as => :mobile_sample_undo_reception, :via => :get
  match '/samples/m/:url_code/receive' => 'samples#mobile_receive', :as => :mobile_sample_receive, :via => :get
  match '/samples/m/:url_code' => 'samples#mobile', :as => :mobile_sample, :via => :get
  resources :specimens, :controller => "samples"

  resources :unused_kit_names

  match '/kits/:id/log' => 'kits#show_log', :as => :show_kit_log, :via => :get
  match '/kits/:id/confirm_claim' => 'kits#confirm_claim', :as => :kit_confirm_claim, :via => :post
  match '/kits/claim' => 'kits#claim', :as => :kit_claim

  match '/admin/researchers/study_filter_results' => 'admin/researchers#study_filter_results', :format => 'csv', :as => :study_filter_results_csv

  resources :kits
  match '/kits/:id/sent' => 'kits#sent', :as => :sent_kit, :via => :post
  match '/kits/:id/returned' => 'kits#returned', :as => :returned_kit, :via => :post
  match '/kits/sent_selected' => 'kits#sent_selected', :as => :sent_selected_kits, :via => :post
  match '/kits/:id/lost' => 'kits#lost', :as => :lost_kit, :via => :post

  resources :traitwise_surveys do
    post 'participate', :on => :member
    post 'synchronize', :on => :member
    post 'download', :on => :member
  end
  match '/traitwise/proxy' => 'traitwise#proxy'
  match '/traitwise/:id' => 'traitwise#index', :as => :take_traitwise_survey
  match '/traitwise/:id/iframe' => 'traitwise#iframe', :as => :traitwise_iframe

  resources :google_surveys do
    post 'participate', :on => :member
    # So that going via login_required when clicking on the link in a reminder e-mail doesn't break the flow,
    # we also support the GET method.
    get 'participate', :on => :member
    post 'synchronize', :on => :member
    post 'send_test_reminder', :on => :member
    match 'download', :on => :member
    match 'download_bypasses', :on => :member
  end
  match '/nonce/:id' => 'nonces#delete', :as => :delete_google_survey_answers, :via => :delete
  match '/google_survey_reminder/edit' => 'google_survey_reminders#edit', :as => :edit_google_survey_reminder
  match '/google_survey_reminder/update' => 'google_survey_reminders#update', :as => :update_google_survey_reminder, :via => :post
  # So that going via login_required when clicking on the link in a reminder e-mail doesn't break the flow,
  # we also support the GET method.
  match '/google_survey_bypass/:token' => 'google_survey_bypasses#record', :as => :google_survey_bypass, :via => [:get, :post]

  resources :google_spreadsheets do
    post 'synchronize', :on => :member
  end

  get "oauth_tokens/authorize"
  get "oauth_tokens/revoke"
  match "oauth_tokens/get_access_token" => 'oauth_tokens#get_access_token', :as => :get_oauth_access_token, :via => :get
  get 'oauth2callback' => 'oauth_tokens#oauth2callback', :as => :oauth2callback
  resources :oauth_tokens, :only => :index

  resources :kit_design_samples
  get 'sample_type_show' => 'sample_types#show'
  resources :sample_types
  resources :units
  resources :device_types
  resources :tissue_types
  resources :kit_designs
  match '/collection_events/claim' => 'studies#claim', :as => :study_claim_kit
  match '/collection_events/:id/users' => 'studies#users', :as => :study_users
  match '/collection_events/:id/sent_kits_to_selected' => 'studies#sent_kits_to_selected', :as => :sent_kits_to_selected_study_users
  match '/collection_events/:id/map' => 'studies#map', :as => :study_map
  match '/collection_events/:study_id/users/:user_id/:status' => 'studies#update_user_status', :as => :study_update_user_status
  match '/collection_events/:id/sent_kits_to_selected' => 'studies#sent_kits_to_selected', :as => :sent_kits_to_selected_study_users, :via => :post
  match '/collection_events/:id/accept_interested_selected' => 'studies#accept_interested_selected', :as => :accept_interested_selected_study_users, :via => :post
  resources :collection_events, :controller => "studies"
  match '/pages/studies', :to => redirect('/pages/collection_events')
  match '/studies/*x', :to => redirect('/collection_events/%{x}')

  get 'third_party/index'
  get 'third_party/study/:id' => 'studies#show_third_party', :as => :third_party_study
  match '/third_party/study/:id/verify_participant_id/:app_token' => 'studies#verify_participant_id', :via => [:get], :as => :verify_third_party_participant_id
  match '/third_party/study/:id/clickthrough_to' => 'studies#clickthrough_to', :via => [:post], :as => :clickthrough_to_third_party
  post '/third_party/add_dataset' => 'studies#add_dataset'
  match '/3p/*x', :to => redirect('/third_party/%{x}')

  get 'open_humans/participate'
  post 'open_humans/disconnect'
  post 'open_humans/tokens', :to => 'open_humans#create_token'
  post 'open_humans/huids', :to => 'open_humans#create_huid'
  get 'open_humans/huids'
  # This callback URL is set on the Open Humans API server
  get 'auth/open-humans/callback' => 'open_humans#callback'

  match '/filters/upload' => 'filters#upload', :as => :upload_filter, :via => :post

  resources :pages
  match '/23andme' => 'pages#show', :id => '23andme', :as => 'twenty3andme'
  match '/23andMe' => 'pages#show', :id => '23andme', :as => 'twenty3andme'
  match '/enrolled', :to => redirect('/users')
  match '/users/initial' => 'users#initial', :as => :initial_user
  match '/users/create_initial' => 'users#create_initial', :as => :create_initial_user
  match '/users/new2' => 'users#new2', :as => :new2_user
  match '/users/accept_enrollment' => 'users#accept_enrollment', :as => :accept_enrollment_user
  match '/users/tos' => 'users#tos', :as => :tos_user
  match '/users/accept_tos' => 'users#accept_tos', :as => :accept_tos_user
  match '/users/consent' => 'users#consent', :as => :consent_user
  match '/users/unauthorized' => 'users#unauthorized', :as => :unauthorized_user
  match '/users/deactivated' => 'users#deactivated', :as => :deactivated_user
  match '/users/created/:id' => 'users#created', :as => :created_user
  match '/users/show_log' => 'users#show_log', :as => :show_log_user
  match '/users/withdraw' => 'users#withdraw', :as => :withdraw_user, :via => :post
  match '/users/withdraw_confirm' => 'users#withdraw_confirm', :as => :withdraw_confirm_user, :via => :post
  match '/users/:switch_to_id/switch_to' => 'users#switch_to', :via => [:post], :as => :switch_to_user
  match '/drb/userlog/:user_id' => 'drb#userlog', :as => :userlog_drb
  match '/user/study/:study_id' => 'users#edit_study', :as => :user_edit_study, :via => :get
  match '/user/study/:study_id' => 'users#update_study', :as => :user_update_study, :via => :post
  match '/users/resend_signup_notification_form' => 'users#resend_signup_notification_form', :as => :resend_signup_notification_form
  match '/users/resend_signup_notification/:id' => 'users#resend_signup_notification', :as => :resend_signup_notification_user
  match '/users/create_researcher', :as => :create_researcher, :via => :post
  match '/users/participant_survey' => 'users#participant_survey'
  resources :shipping_addresses
  match '/user/shipping_address' => 'users#shipping_address', :as => 'user_shipping_address'
  match '/user/edit' => 'users#edit', :as => 'edit_user', :method => :get
  match '/user/update' => 'users#update', :as => 'update_user', :method => :post
  resources :users

  resource :session
  match '/login' => 'sessions#new', :as => :login

app/models/study.rb
class Study < ActiveRecord::Base
  stampable
  acts_as_paranoid_versioned :version_column => :lock_version
  acts_as_api

  belongs_to :researcher, :class_name => "User"
  belongs_to :irb_associate, :class_name => "User"

  has_many :kit_designs
  has_many :kits
  # BEWARE: study.study_participants includes test users... I can't find a way to exclude them here. Use
  # study.study_participants.real (a scope on the study_participants model) instead. Ward, 2011-07-31
  has_many :study_participants, :dependent => :destroy
  has_many :users, :through => :study_participants, :conditions => ['users.is_test = ?', false]

  validates_uniqueness_of :name
  validates_presence_of   :name
  validates_presence_of   :researcher_id

  validates_presence_of   :participant_description
  validates_presence_of   :researcher_description

  validates_presence_of :irb_associate, :message => ' is required if the study is approved', :if => :is_approved?

  before_validation :normalize_third_party_fields
  validates_format_of :participation_url, {
    :with => %r{^https?://[^/\s]{4,}(/\S*)?$},
    :message => 'must be a valid http:// or https:// web address',
    :allow_nil => true
  }

  scope :requested, where('requested = ?',true)
  scope :approved, where('approved = ?',true)
  scope :draft, where('requested = ? and approved = ?',false,false)
  scope :not_third_party, where('participation_url is ?', nil)
  scope :third_party, where('participation_url is not ?', nil)
  scope :open_now, where('open = ? and approved = ?',true,true)
  scope :not_open, where('open = ?',false)

  scope :accessible, lambda { |user|
    if user.is_admin? then
      all
    elsif user.is_researcher? then
      where("researcher_id = ?",user.id)
    end
  }
  scope :visible_to, lambda { |current_user| accessible(current_user) }

  def is_approved?
    self.approved
  end

  def is_open?
    self.open
  end

  def normalize_third_party_fields
    @is_third_party = self.is_third_party if @is_third_party.nil?
    self.participation_url = nil if !@is_third_party
  end

  def is_third_party
    !self.participation_url.nil?
  end

  def is_third_party=(bool)
    @is_third_party = (bool && bool.to_s != '0')
  end

  def personalized_participation_url(user)
    s = participation_url
    unless s.match(/\?.*=$/)    # url?code=
      s << (s.match(/\?/) ? '&' : '?')
      s << 'study_id=' << id.to_s
      s << '&participant_id='
    end
    s << user.app_token("Study##{self.id}")
  end

  def status
    if self.open and self.approved then
      'open'
    elsif self.approved then
      'approved'
    elsif self.requested then
      'requested'
    else
      'draft'
    end
  end

  def long_status
    if self.open and self.approved then
      'approved, open to participants'
    elsif self.approved then
      'approved, closed'
    elsif self.requested then
      'pending admin approval'
    else
      'draft'
    end
  end

  def study_type
    return 'study or collection event' if !id
    is_third_party ? 'activity' : 'collection event'
  end

  api_accessible :id do |t|
    t.add :name
  end

  api_accessible :public, :extend => :id do |t|
  end

  api_accessible :researcher, :extend => :public do |t|
  end

  api_accessible :privileged, :extend => :public do |t|
  end

  def api_key
    self.class.generate_api_key id
  end

  def self.find_by_api_key token
    id_s, hmac = token.split '/'
    if token != generate_api_key(id_s)
      raise ActiveRecord::RecordNotFound
    end
    study = approved.third_party.where(:id => id_s.to_i).first
    if !study
      raise ActiveRecord::RecordNotFound
    end
    return study
  end

  private

  def self.generate_api_key id
    secret = Tapestry::Application.config.secret_token
    if secret.nil? or secret.length < 16
      raise "Installation problem: Application.config.secret_token not properly defined"
    end
    hmac = OpenSSL::HMAC.hexdigest(OpenSSL::Digest::Digest.new('SHA1'),
                                   secret, "#{self.class}--#{id}")
    "#{id}/#{hmac}"
  end
end

app/controllers/admin/studies_controller.rb
class Admin::StudiesController < Admin::AdminControllerBase

  def index
    respond_to do |format|
      format.html
      format.csv { send_data csv_for_studies(@unpaginated_studies), {
                     :filename    => 'PGP Application Studies.csv',
                     :type        => 'application/csv',
                     :disposition => 'attachment' } }
    end
  end

  def edit
    @study = Study.find(params[:id])
  end

  def update
    @study = Study.find(params[:id])
    params[:study].delete :is_third_party
    @study.irb_associate = params[:study].delete(:irb_associate)
    @was_open = @study.open && @study.approved
    @study.open = params[:study].delete(:open)
    @approved = params[:study].delete(:approved)
    if ((@study.approved != @approved) and (@study.approved == false)) then
      @study.date_approved = Time.now()
    end
    @study.approved = @approved
    @study.requested = false if @study.approved
    @study.date_opened = Time.now if @study.open and @study.approved and !@was_open

    if @study.update_attributes(params[:study])
      flash[:notice] = 'Study updated.'
      redirect_to admin_researchers_url
    else
      render :action => 'edit' 
    end
  end

  def destroy
    @study = Study.find params[:id]

    if @study.destroy
      flash[:notice] = 'Study deleted.'
      redirect_to admin_studies_url
    else
      render :action => 'index'
    end
  end

end

app/views/studies/claim.html.erb
<h2>Claim a kit</h2>

<p>If you have received a sample collection kit in the mail, please
claim your kit here.</p>

<p>Each kit has a nickname, which was randomly chosen from boston area
street names.</p>

<p>You can find your kit&rsquo;s nickname printed on the specimen
vials (e.g., &ldquo;Kit: Yourkitname&rdquo;).  Please check to make
sure that all vials have the same kit name prior to claiming your
kit.</p>

<h3>What is the nickname of your kit?</h3>

<%= form_tag kit_claim_path, :method => 'post' do %>
  <div class="field">
    <%= text_field_tag :name %>
    <%= submit_tag("Claim", :name => nil) %>
  </div>
  </p>
<% end %>

app/views/studies/edit.html.erb
<h2>Edit <%= @study.study_type %></h2>

<%= render 'form' %>

app/views/studies/index.html.erb
<h2>Collection events</h2>
<%= button_to 'Create collection event', new_collection_event_path, :class => 'btn btn-primary pull-right', :style => 'margin-right: 2em', :method => :get %>

<% if current_user.is_admin? %>
<p>Because you are an administrator, this page lists all collection events by any researcher.</p>
<% else %>
<p>This is the list of your collection events, as well as any collection events another researcher has granted you rights to.</p>
<% end %>

<% if @studies.count > 0 %>
<%= render :partial => 'admin/researchers/studiestable', :locals => { :studies => @studies, :type => 'all', :who => 'researcher' } %>
<% end %>

app/views/studies/map.html.erb
<h2><%= @study.name %></h2>


<%= gmaps("markers" => {"data" => @json, "options" => {"custom_infowindow_class" => "yellow" } }) %>

<p><%= image_tag('yellow.png') %> Kit created/shipped | <%= image_tag('green.png') %> Kit claimed | <%= image_tag('blue.png') %> Kit returned | <%= image_tag('brown.png') %> Kit received by researcher</p>

<table>
<tr>
<td>
<table class="admin_table">
<tr>
<th colspan="6" align="center">Kits</th>
</tr>
<tr>
<td>Created:</td><td><%= @study.kits.not_yet_shipped.count %></td>
<td>Shipped:</td><td><%= @study.kits.shipped.count %></td>
<td>Claimed:</td><td><%= @study.kits.claimed.count %></td>
</tr>
<tr>
<td>Returned:</td><td><%= @study.kits.returned.count %></td>
<td>Received:</td><td><%= @study.kits.received.count %></td>
</tr>
<tr>
<td colspan="2" align="right">Total:</td><td colspan="2" align="left"><%= @study.kits.count %></td>
</tr>
</table>
</td>
<td>
<table class="admin_table">
<tr>
<th colspan="6" align="center">Participants</th>
</tr>
<tr>
<td>Undecided:</td><td><%= @study.study_participants.undecided.count %></td>
<td>Interested:</td><td><%= @study.study_participants.interested.count %></td>
<td>Not accepted:</td><td><%= @study.study_participants.not_accepted.count %></td>
</tr>
<tr>
<td>Not interested:</td><td><%= @study.study_participants.not_interested.count %></td>
<td>Accepted:</td><td><%= @study.study_participants.accepted.count %></td>
<td>Removed:</td><td><%= @study.study_participants.removed.count %></td>
</tr>
<tr>
<td>&nbsp;</td><td>&nbsp;</td>
<td>Total:</td><td><%= @study.study_participants.real.count %></td>
<td>&nbsp;</td><td>&nbsp;</td>
</tr>
</table>
</tr>
</table>

app/views/studies/show_third_party.html.erb
<p><i>Note: This activity is <b>not</b> conducted by or supervised by
the Personal Genome Project.  The description below may include links
to an independent web site.</i></p>

<h2><%= @study.name %></h2>

<%= raw RedCloth.new(@study.participant_description).to_html %>

<p><b>Researcher</b>: <%= @study.researcher.full_name %>, <%= @study.researcher.researcher_affiliation %></p>

<div style="width:300px;padding:1em;border:1px dashed #866">
  Clicking the "participate" button below will take you to the
  project&rsquo;s web site.  A token will be passed to confirm that
  you are a PGP participant &mdash; but the project will not yet be
  told <i>which</i> PGP participant you are.  You may have an
  opportunity to make that linkage later to enable certain features,
  such as adding research data you receive from third party activities
  to your public PGP profile.
  <br />&nbsp;
  <div style="text-align:center">
    <%= button_to 'Participate', clickthrough_to_third_party_path(@study) %>
  </div>
</div>

app/views/studies/users.html.erb
<%- content_for :head do -%>
<%= javascript_include_tag 'apply_action' %>
<%- end -%>

<% content_for :js do %>
jQuery(function() {
    var $ = jQuery.noConflict();
    $(document).ready(function() {
        $('#study_users').removeClass('admin_table');
        x = $('#study_users').dataTable( {
            "bProcessing": true,
            "bJQueryUI": true,
            "sDom": '<"H"lipfr>t<"F">',
            "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
            "iDisplayLength": -1,
            "aoColumnDefs": [
              { "bSearchable": false, "aTargets": [2] },
              { "bVisible": false, "aTargets": [1] } ]
            } );
        x.fnSkipMissingDataProps();
        x.fnSetFilteringDelay();
    } );
    $('a[select-status]').click(function(){
        $('#study_users_wrapper div.dataTables_filter input[type=text]').
            val($(this).attr('select-status')).
            trigger('keyup');
        return false;
    });
});
<% end %>
<% content_for :head do %>
  <%= javascript_include_tag 'jquery.dataTables.fnSetFilteringDelay' %>
  <%= javascript_include_tag 'jquery.dataTables.fnSkipMissingDataProps' %>
  <%= javascript_include_tag 'jquery.dataTables.renderers' %>
<% end %>

<h2><%= @study.name %>: participants</h2>

<% if current_user.is_admin? %>
<div style="float:right">
  <table><tr><td valign="bottom" style="background:#ffffdd;padding:0 .5em">
	Upload a CSV file with participant ID tokens:<br />
<%= form_for :upload, :url => upload_filter_path, :html => { :multipart => true } do |f| %>
<%= hidden_field_tag :target_class, 'User' %>
<%= hidden_field_tag :target_id_attribute, 'app_token' %>
<%= hidden_field_tag :"target_id_attribute_args[]", "Study##{@study.id}" %>
<%= hidden_field_tag :return_to, request.path %>
<%= file_field_tag 'file' %><br />
<%= f.submit 'Upload CSV and select users by token' %>
<% end %>
<br />
	Upload a CSV file with participant hex IDs:<br />
<%= form_for :upload, :url => upload_filter_path, :html => { :multipart => true } do |f| %>
<%= hidden_field_tag :target_class, 'User' %>
<%= hidden_field_tag :target_id_attribute, 'hex' %>
<%= hidden_field_tag :return_to, request.path %>
<%= file_field_tag 'file' %><br />
<%= f.submit 'Upload CSV and select users by hex' %>
<% end %>
<br />
	Upload a CSV file with participant names:<br />
<%= form_for :upload, :url => upload_filter_path, :html => { :multipart => true } do |f| %>
<%= hidden_field_tag :target_class, 'User' %>
<%= hidden_field_tag :target_id_attribute, 'full_name' %>
<%= hidden_field_tag :target_scope, 'enrolled' %>
<%= hidden_field_tag :return_to, request.path %>
<%= file_field_tag 'file' %><br />
<%= f.submit 'Upload CSV and select users by full name' %>
<% end %>
  </td><td valign="bottom">
	or
  </td><td valign="bottom" style="background:#ffffdd;padding:0 .5em">
	<div style="text-align:right">
	  <%= button_to 'Select all', request.path, :method => :get %>
	</div>
      </td></tr>
    <tr><td colspan="3" style="text-align:right">
	Apply to <%= @participants.size %> selected participants:
	<%= form_tag '', :method => :post do %>
	<%= hidden_field_tag :study_id, @study.id %>
	<%= hidden_field_tag :return_to, request.fullpath %>
	<%= hidden_field_tag :selection_id, @selection.id if @selection %>
	<%= select_tag :apply_action, options_for_select([['(Choose action)',nil], ['Update status from "interested" to "accepted"',accept_interested_selected_study_users_path], ['Record that kits have been sent',sent_kits_to_selected_study_users_path]]) %>
	<%= submit_tag 'Apply', :confirm => "Confirm:  Do you really want to apply this action to all #{@participants.size} selected participants?" %>
	<% end %>
    </td></tr>
  </table>
</div>
<% end %>

<p>Showing <%= @participants.count %> of <%= @all_participants.count %> participants who have indicated whether they are interested in this <%= @study.study_type %>.</p>

<table class="admin_table">
<tr>
<td><a href="#" select-status="participant:undecided">Undecided</a>:</td><td>
    <b><%= "#{@participants.undecided.count} / " if @selection %></b>
    <%= @all_participants.undecided.count %></td>
<td><a href="#" select-status="participant:interested">Interested</a>:</td><td>
    <b><%= "#{@participants.interested.count} / " if @selection %></b>
    <%= @all_participants.interested.count %></td>
<td><a href="#" select-status="participant:notaccepted">Not accepted</a>:</td><td>
    <b><%= "#{@participants.not_accepted.count} / " if @selection %></b>
    <%= @all_participants.not_accepted.count %></td>
</tr>
<tr>
<td><a href="#" select-status="participant:notinterested">Not interested</a>:</td><td>
    <b><%= "#{@participants.not_interested.count} / " if @selection %></b>
    <%= @all_participants.not_interested.count %></td>
<td><a href="#" select-status="participant:accepted">Accepted</a>:</td><td>
    <b><%= "#{@participants.accepted.count} / " if @selection %></b>
    <%= @all_participants.accepted.count %></td>
<td><a href="#" select-status="participant:removed">Removed</a>:</td><td>
    <b><%= "#{@participants.removed.count} / " if @selection %></b>
    <%= @all_participants.removed.count %></td>
</tr>
</table>

<p>Status of last kit sent to each participant:
  <br />
  <%= raw @kit_status_count.collect { |s,n| "#{n} #{link_to s, '#', :"select-status"=>'kit:'+s}" }.join ", " %>.
</p>

<div style="clear:both"></div>

<% if not @participants.empty? %>
<% rownum = 0 %>

<table class="admin_table" id="study_users" style="width:100%">
  <thead>
    <tr>
      <th>#</th>
      <th style="display:none"></th><%# searchable status %>
      <% if @study.is_third_party %>
      <th>Study-specific participant ID</th>
      <th>Status</th>
      <% else %>
      <th>Name</th>
      <th>Status</th>
      <th></th><%# remove/accept actions %>
      <th>Kit last sent</th>
      <th>Kit claimed</th>
      <th>Kit status</th>
      <th>Age&nbsp;(d)</th>
      <th>Other kits?</th>
      <% end %>
      <% if @selection %>
      <th>Action parameters</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @sorted_participants.each do |p| %>
    <% claimed_kit, claimed_kit_at = p.claimed_kit_sent_at(p.kit_last_sent_at) %>
    <tr class="<%= cycle 'even', 'odd' %>">
      <td><%= rownum += 1 %></td>
      <td style="display:none">
        participant:<%= p.pretty_status.downcase.gsub(' ','') %>
        kit:<%= claimed_kit ? claimed_kit.short_status : 'none' %>
      </td>
      <% if @study.is_third_party %>
      <td><%= p.user.app_token "Study##{@study.id}" %></td>
      <td><%= p.pretty_status %></td>
      <% else %>
      <td><%= current_user.is_admin? ? link_to(p.user.full_name, admin_user_url(p.user)) : p.user.full_name %></td>
      <td><%= p.pretty_status %></td>
      <td>
      <% if p.status == 2 %>
        <%= link_to('accept', study_update_user_status_path(p.study,p.user,'accepted'), :method => :post) %>
      <% elsif p.status == 3 %>
        <%= link_to('remove', study_update_user_status_path(p.study,p.user,'removed'), :method => :post) %>
      <% elsif p.status == StudyParticipant::STATUSES['not accepted'] %>
        <%= link_to('accept', study_update_user_status_path(p.study,p.user,'accepted'), :confirm => 'Are you sure? This user has already been marked "not accepted".', :method => :post) %>
      <% end %>
      </td>
      <td><%= p.kit_last_sent_at %></td>

      <td><%= link_to claimed_kit.name, kit_path(claimed_kit) if claimed_kit %></td>
      <td><%= claimed_kit.short_status if claimed_kit %></td>
      <td style="text-align:right"><%= (claimed_kit.age/86400).floor if claimed_kit %></td>
      <td><%=raw p.user.kits.select { |k| k.study_id==p.study_id and (!claimed_kit or k.id != claimed_kit.id) }.collect { |k| link_to k.name, kit_path(k) }.join(' ') %></td>
      <% end %>

      <% if @selection %>
      <td><%= @study_participant_info[p.id].inspect %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<% else %>
<p>This <%= @study.study_type %> has no participants yet.</p>
<% end %>