config/routes.rb
    post 'synchronize', :on => :member
    post 'download', :on => :member
  end
  match '/traitwise/proxy' => 'traitwise#proxy'
  match '/traitwise/:id' => 'traitwise#index', :as => :take_traitwise_survey
  match '/traitwise/:id/iframe' => 'traitwise#iframe', :as => :traitwise_iframe

  resources :google_surveys do
    post 'participate', :on => :member
    # So that going via login_required when clicking on the link in a reminder e-mail doesn't break the flow,
    # we also support the GET method.
    get 'participate', :on => :member
    post 'synchronize', :on => :member
    post 'send_test_reminder', :on => :member
    match 'download', :on => :member
    match 'download_bypasses', :on => :member
  end
  match '/nonce/:id' => 'nonces#delete', :as => :delete_google_survey_answers, :via => :delete
  match '/google_survey_reminder/edit' => 'google_survey_reminders#edit', :as => :edit_google_survey_reminder
  match '/google_survey_reminder/update' => 'google_survey_reminders#update', :as => :update_google_survey_reminder, :via => :post
  # So that going via login_required when clicking on the link in a reminder e-mail doesn't break the flow,
  # we also support the GET method.
  match '/google_survey_bypass/:token' => 'google_survey_bypasses#record', :as => :google_survey_bypass, :via => [:get, :post]

  resources :google_spreadsheets do
    post 'synchronize', :on => :member
  end

  get "oauth_tokens/authorize"
  get "oauth_tokens/revoke"
  match "oauth_tokens/get_access_token" => 'oauth_tokens#get_access_token', :as => :get_oauth_access_token, :via => :get
  get 'oauth2callback' => 'oauth_tokens#oauth2callback', :as => :oauth2callback
  resources :oauth_tokens, :only => :index

  resources :kit_design_samples
  get 'sample_type_show' => 'sample_types#show'
  resources :sample_types
  resources :units
  resources :device_types
  resources :tissue_types
  resources :kit_designs
  match '/collection_events/claim' => 'studies#claim', :as => :study_claim_kit
  match '/collection_events/:id/users' => 'studies#users', :as => :study_users
  match '/collection_events/:id/sent_kits_to_selected' => 'studies#sent_kits_to_selected', :as => :sent_kits_to_selected_study_users
  match '/collection_events/:id/map' => 'studies#map', :as => :study_map
  match '/collection_events/:study_id/users/:user_id/:status' => 'studies#update_user_status', :as => :study_update_user_status
  match '/collection_events/:id/sent_kits_to_selected' => 'studies#sent_kits_to_selected', :as => :sent_kits_to_selected_study_users, :via => :post
  match '/collection_events/:id/accept_interested_selected' => 'studies#accept_interested_selected', :as => :accept_interested_selected_study_users, :via => :post
  resources :collection_events, :controller => "studies"
  match '/pages/studies', :to => redirect('/pages/collection_events')
  match '/studies/*x', :to => redirect('/collection_events/%{x}')

  get 'third_party/index'
  get 'third_party/study/:id' => 'studies#show_third_party', :as => :third_party_study
  match '/third_party/study/:id/verify_participant_id/:app_token' => 'studies#verify_participant_id', :via => [:get], :as => :verify_third_party_participant_id
  match '/third_party/study/:id/clickthrough_to' => 'studies#clickthrough_to', :via => [:post], :as => :clickthrough_to_third_party
  post '/third_party/add_dataset' => 'studies#add_dataset'
  match '/3p/*x', :to => redirect('/third_party/%{x}')

  get 'open_humans/participate'
  post 'open_humans/disconnect'
  post 'open_humans/tokens', :to => 'open_humans#create_token'
  post 'open_humans/huids', :to => 'open_humans#create_huid'
  get 'open_humans/huids'
  # This callback URL is set on the Open Humans API server
  get 'auth/open-humans/callback' => 'open_humans#callback'

  match '/filters/upload' => 'filters#upload', :as => :upload_filter, :via => :post

  resources :pages
  match '/23andme' => 'pages#show', :id => '23andme', :as => 'twenty3andme'
  match '/23andMe' => 'pages#show', :id => '23andme', :as => 'twenty3andme'
  match '/enrolled', :to => redirect('/users')
  match '/users/initial' => 'users#initial', :as => :initial_user
  match '/users/create_initial' => 'users#create_initial', :as => :create_initial_user
  match '/users/new2' => 'users#new2', :as => :new2_user
  match '/users/accept_enrollment' => 'users#accept_enrollment', :as => :accept_enrollment_user
  match '/users/tos' => 'users#tos', :as => :tos_user
  match '/users/accept_tos' => 'users#accept_tos', :as => :accept_tos_user
  match '/users/consent' => 'users#consent', :as => :consent_user
  match '/users/unauthorized' => 'users#unauthorized', :as => :unauthorized_user
  match '/users/deactivated' => 'users#deactivated', :as => :deactivated_user
  match '/users/created/:id' => 'users#created', :as => :created_user
  match '/users/show_log' => 'users#show_log', :as => :show_log_user
  match '/users/withdraw' => 'users#withdraw', :as => :withdraw_user, :via => :post
  match '/users/withdraw_confirm' => 'users#withdraw_confirm', :as => :withdraw_confirm_user, :via => :post
  match '/users/:switch_to_id/switch_to' => 'users#switch_to', :via => [:post], :as => :switch_to_user
  match '/drb/userlog/:user_id' => 'drb#userlog', :as => :userlog_drb
  match '/user/study/:study_id' => 'users#edit_study', :as => :user_edit_study, :via => :get
  match '/user/study/:study_id' => 'users#update_study', :as => :user_update_study, :via => :post
  match '/users/resend_signup_notification_form' => 'users#resend_signup_notification_form', :as => :resend_signup_notification_form
  match '/users/resend_signup_notification/:id' => 'users#resend_signup_notification', :as => :resend_signup_notification_user
  match '/users/create_researcher', :as => :create_researcher, :via => :post
  match '/users/participant_survey' => 'users#participant_survey'
  resources :shipping_addresses
  match '/user/shipping_address' => 'users#shipping_address', :as => 'user_shipping_address'
  match '/user/edit' => 'users#edit', :as => 'edit_user', :method => :get
  match '/user/update' => 'users#update', :as => 'update_user', :method => :post
  resources :users

  resource :session
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/signup' => 'users#new', :as => :signup
  match '/researcher_signup' => 'users#new_researcher', :as => :researcher_signup
  match '/signup_researcher' => 'users#new_researcher', :as => :researcher_signup
  match '/register' => 'users#create', :as => :register
  match '/activate/:code' => 'users#activate', :as => :activate
  resource :password
  resources :accepted_invites

  resources :content_areas do
    resources :exams do
      resources :exam_questions do
        member do
          post :answer
        end
      end
    end
    match 'exams/:id/start' => 'exams#start', :via => [:get, :post], :as => 'start_exam'
    match 'exams/:id/retake' => 'exams#retake', :via => [:get, :post], :as => 'retake_exam'
  end

  namespace :screening_surveys do
      resource :residency
      resource :family
      resource :privacy
  end

  resource :screening_surveys
  match '/screening_survey_results' => 'screening_surveys#results', :as => :screening_survey_results
  resources :waitlist_resubmissions
  resource :phr
  resource :consent_review
  resource :screening_submission
  resource :participation_consent
  resource :enrollment_queue
  resource :baseline_trait_collection_notification
  match '/baseline_trait_collection_notifications/done' => 'baseline_trait_collection_notifications#done', :as => :done_baseline_trait_collection_notification
  resource :identity_verification_notification
  match '/identity_verification_notifications/done' => 'identity_verification_notifications#done', :as => :done_identity_verification_notification
  match '/named_proxies/done' => 'named_proxies#done', :as => :done_named_proxy
  resources :named_proxies
  resources :user_files
  match '/user_file/download/:id' => 'user_files#download', :as => :user_file_download
  match '/user_files/:id/reprocess' => 'user_files#reprocess', :as => :reprocess_user_file
  match '/user_files/:id/longupload' => 'user_files#longupload', :as => :longupload_user_file, :via => :post
  match '/datasets/:id/download' => 'datasets#download', :as => :dataset_download
  get '/dataset_reports/:id' => 'dataset_reports#show', :as => :dataset_report


  resources :specimen_analysis_data
  match '/specimen_analysis_data/:id/publish' => 'specimen_analysis_data#publish', :as => :publish_specimen_analysis_data
  resource :trait_collection
  resource :distinctive_traits_survey
  resource :pledge
  resource :identity_confirmation
  resource :enrollment_application
  resources :eligibility_screening_results
  resources :enrollment_application_results
  resources :mailing_list_subscriptions
  resources :international_participants
  match '/family_relation/confirm/:id' => 'family_relations#confirm', :as => :confirm_family_relation
  match '/family_relation/reject/:id' => 'family_relations#reject', :as => :reject_family_relation
  match '/family_relations/update' => 'family_relations#update', :as => :update_has_family_relations
  resources :family_relations
  match '/safety_questionnaires/require' => 'safety_questionnaires#require', :as => :require_safety_questionnaire
  resources :safety_questionnaires
  match '/admin/safety_questionnaires' => 'admin/safety_questionnaires#index', :as => :admin_safety_questionnaires
  match '/admin/scoreboards' => 'admin/scoreboards#index', :as => :admin_scoreboards
  match '/admin/researchers' => 'admin/researchers#index', :as => :admin_researchers
  match '/admin/users/enroll' => 'admin/users#enroll', :as => :admin_enroll_users
  match '/admin/users/enroll_single_user/:id' => 'admin/users#enroll_single_user', :as => :admin_enroll_single_user
  match '/admin/users/twins' => 'admin/users#twins', :as => :admin_twins_users
  match '/admin/users/active' => 'admin/users#active', :as => :admin_active_users

app/controllers/admin/datasets_controller.rb
class Admin::DatasetsController < Admin::AdminControllerBase
  
  before_filter :set_dataset, :only => [:edit, :update, :release, :notify, :reprocess]

  def index
    @datasets = Dataset.includes(:participant).all

    @users = Array.new()
    # Make a list of every participant that has taken each trait survey
    TRAIT_SURVEY_IDS.each do |ts_id|
      if @users.empty? then
        @users = Nonce.where("target_class=? and target_id = ? and used_at is not null",'GoogleSurvey',ts_id).map { |n| n.owner_id }
      else
       @users = @users & Nonce.where("target_class=? and target_id = ? and used_at is not null",'GoogleSurvey',ts_id).map { |n| n.owner_id }
      end
    end
  end

  def edit
  end

  def new
    @dataset = Dataset.new
  end


  def release
    @dataset.released_to_participant = true
    @dataset.save!
    @dataset.participant.log("Dataset '#{@dataset.name}' with id #{@dataset.id} was released to this participant")

    notify
  end

  def notify
    UserMailer.dataset_notification_message(specimen_analysis_data_index_url, @dataset.participant, @dataset).deliver

    @dataset.sent_notification_at = Time.now()
    @dataset.save!

    @dataset.participant.log("Notified about release of dataset with id #{@dataset.id}")

    redirect_to admin_datasets_path
  end

  def create
    @dataset = Dataset.new(params[:dataset])

    if @dataset.save
      flash[:notice] = 'Dataset was successfully created.'
      maybe_submit_to_get_evidence
      redirect_to admin_datasets_path
    else
      render :action => 'new'
    end
  end

  def update
    if @dataset.update_attributes(params[:dataset])
      flash[:notice] = 'Dataset was successfully updated.'
      maybe_submit_to_get_evidence
      redirect_to admin_datasets_path
    else
      render :action => "edit"
    end
  end

  def destroy
    @dataset = Dataset.find(params[:id])
    @dataset.destroy

    redirect_to(admin_datasets_url)
  end

  def reprocess
    submit!
    flash[:notice] = "Dataset ##{@dataset.id} re-submitted to GET-Evidence."
    redirect_to(params[:return_to] || :back)
  end

  private
  def set_dataset
    @dataset = Dataset.find(params[:id])
  end

  def maybe_submit_to_get_evidence
    return unless params[:dataset][:submit_to_get_e]
    submit!
  end

  def submit!
    begin
      @submitopts = {}
      @submitopts[:make_public] = !!@dataset.published_at
      if @dataset.published_anonymously_at and !@dataset.published_at
        @submitopts[:human_id] = ''
        @submitopts[:name] = ''
      end
      @dataset.submit_to_get_evidence!(@submitopts)
    rescue Exception => e
      # Callout error
      logger.debug "Error contacting GET-Evidence: #{e.inspect}"
      flash[:error] = "There was an error contacting GET-Evidence. Please try again later."
    end
  end

end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  skip_before_filter :login_required, :only => [:download, :show]
  skip_before_filter :ensure_enrolled, :only => [:download, :show]

  def download
    @dataset = Dataset.find(params[:id])
    if @dataset.published_at or
        @dataset.published_anonymously_at or
        (current_user and
         (current_user.is_admin? or
          (@dataset.participant_id == current_user.id and
           @dataset.released_to_participant)))
      x = @dataset.download_url
      return redirect_to(x) if x
      flash[:error] = "Sorry, this file is temporarily unavailable."
      return redirect_to :back
    end
    flash[:error] = "The file you requested does not seem to exist."
    return redirect_to public_genetic_data_path
  end
end

app/views/admin/datasets/_form.html.erb
<%= error_messages_for :dataset, :header_message => 'Error: data could not be saved.', :message => nil %>

<%= form_for [:admin, @dataset] do |f| -%>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :human_id, "Participant hex id" %><br />
    <% if @dataset.released_to_participant then -%> 
      <%= @dataset.human_id %>
    <% else -%>
      <%= f.text_field :human_id %>
    <% end -%>
  </div>
  <div class="field">
    <%= f.label :locator, 'Warehouse locator' %><br />
    <% if @dataset.released_to_participant then -%> 
      <%= @dataset.locator %>
    <% else -%>
      <%= f.text_field :locator, :size => 80 %>
    <% end -%>
  </div>
  <div class="field">
    <%= f.label :researcher_notes, 'Researcher notes (not visible to participant):' %><br />
    <%= f.text_area :researcher_notes, :cols => 80 %>
  </div>
  <div class="field">
    <%= f.label :submit_to_get_e, 'Submit to GET-Evidence:' %><br />
    <%= f.check_box :submit_to_get_e, { :checked => (@dataset.released_to_participant ? false : true) } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/datasets/edit.html.erb
<h2>Edit dataset</h2>

<%= render 'form' %>

app/views/admin/datasets/index.html.erb
<%= button_to 'Create new dataset', new_admin_dataset_path, :class => 'btn btn-primary pull-right', :method => 'get' %>

<h2>Datasets</h2>
  <table class="admin_table table">
  <tr>
    <td><strong>All:</strong></td><td align="right"><%= @datasets.size %></td>
    <td><strong>Released to participant:</strong></td><td align="right"><%= Dataset.released_to_participant.size %></td>
    <td><strong>Not released to participant:</strong></td><td align="right"><%= Dataset.not_released_to_participant.size %></td>
    <td><strong>Age of oldest unreleased dataset:</strong></td><td align="right"><%= Dataset.not_released_to_participant.size > 0 ? distance_of_time_in_words_to_now(Dataset.not_released_to_participant.minimum(:created_at)) : 'all datasets released!' %></td>
  </tr>
  <tr>
    <td><strong>Published:</strong></td><td align="right"><%= Dataset.published.size %></td>
    <td><strong>Published anonymously:</strong></td><td align="right"><%= Dataset.published_anonymously.size %></td>
    <td><strong>Seen by participant:</strong></td><td align="right"><%= Dataset.seen_by_participant.size %></td>
    <td><strong>Released to but not seen by participant:</strong></td><td align="right"><%= Dataset.released_to_but_not_seen_by_participant.size %></td>
  </tr>
  </table>

<table class="admin_table table table-hover">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Status</th>
    <th>Hex ID</th>
    <th>Released to participant</th>
    <th>Participant notified</th>
    <th>Seen by participant</th>
    <th>Published</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @datasets.each do |dataset| -%>
    <tr class="<%= cycle 'even', 'odd' %>">
      <td><%=  dataset.id %></td>
      <td><%= link_to_if dataset.location, dataset.name, dataset.location %></td>
      <td>
        <% if dataset.processing_status then -%>
          <%= dataset.processing_status[:status] %>
          <% if dataset.processing_status[:status] == 'finished' or dataset.processing_status[:status] == 'failed' -%>
	          <%= button_to 'Reprocess', admin_reprocess_dataset_path(dataset), :return_to => request.path, :method => 'post', :class => 'btn btn-mini' %>
          <% end -%>
        <% end -%>
      </td>
      <td>
	<%= link_to dataset.human_id, public_profile_path(dataset.human_id) if dataset.human_id %>
	<%= link_to "(##{dataset.participant_id})", admin_user_url(dataset.participant_id) %>
      </td>
      <td><%= dataset.released_to_participant ? 'Yes' : 'No' %></td>
      <td><%= dataset.sent_notification_at.to_s %></td>
      <td><%= dataset.seen_by_participant_at.to_s %></td>
      <td>
         <% if not dataset.published_at.nil? then -%>
           <%= dataset.published_at.to_s %>
         <% elsif not dataset.published_anonymously_at.nil? then -%>
           <%= dataset.published_anonymously_at.to_s %><br/><i>anonymously</i>
         <% end -%>
        <% if (not dataset.published_at.nil? or not dataset.published_anonymously_at.nil?) and not @users.include?(dataset.participant_id) -%>
          <br/><strong>Trait surveys incomplete</strong>
        <% end -%>
      </td>
      <td><%= link_to 'Download', dataset_download_path(dataset) %></td>
      <td><%= link_to 'Edit', edit_admin_dataset_path(dataset) %></td>

      <% if not dataset.released_to_participant then -%>

      <td><%= link_to 'Destroy', [:admin, dataset], :confirm => 'Are you sure you want to delete this dataset?', :method => :delete %></td>
      <td><%= link_to('Notify participant', admin_dataset_release_participant_url(dataset), :confirm => 'Are you sure you want to release this dataset to the participant and notify them of its existence?') if dataset.participant && (!dataset.participant.deactivated_at || dataset.participant.can_reactivate_self) && !dataset.participant.suspended_at %></td>

      <% elsif dataset.sent_notification_at and not dataset.seen_by_participant_at then -%>

      <td></td>
      <td><%= link_to('Re-notify participant', admin_dataset_notify_participant_url(dataset), :confirm => 'Are you sure you want to re-notify this participant of the release of this dataset?') if dataset.participant && (!dataset.participant.deactivated_at || dataset.participant.can_reactivate_self) && !dataset.participant.suspended_at %></td>

      <% else %>

      <td></td><td></td>

      <% end -%>

    </tr>
  <% end %>
</table>

app/views/admin/datasets/new.html.erb
<h2>New dataset</h2>

<%= render 'form' %>