config/routes.rb
Tapestry::Application.routes.draw do
  root :to => 'pages#show', :id => 'home'

  match '/study_guide_pages/:exam_id/:ordinal' => 'study_guide_pages#show', :as => :show_study_guide_page
  match '/study_guide_pages/:exam_id' => 'study_guide_pages#index', :as => :study_guide_page

  resources :google_spreadsheets

  resources :withdrawal_comments
  resources :permissions
  get 'permissions/update_subject_select'
  get 'permissions/update_subject_select/:subject_class' => 'permissions#update_subject_select'
  get 'permissions/update_subject_select/:subject_class/:id' => 'permissions#update_subject_select'

  resources :plates
  match '/plates/m/:url_code' => 'plates#mobile', :as => :mobile_plate, :via => :get
  match '/plates/:plate_id/assign/:plate_layout_position_id/:sample_id' => 'plates#mobile_assign_position', :as => :mobile_assign_plate_position, :via => :post
  match '/plates/:plate_id/destroy/:plate_layout_position_id' => 'plates#mobile_destroy_position', :as => :mobile_destroy_plate_position, :via => :post
  match '/plates/select_layout_mask/:url_code/:plate_layout_mask_id' => 'plates#mobile_select_layout_mask', :as => :mobile_select_plate_layout_mask, :via => :post
  match '/plates/mobile_stop/:id' => 'plates#mobile_stop', :as => :mobile_stop_plate, :via => :post
  match '/plates/:plate_id/destroy_sample/:plate_layout_position_id' => 'plates#destroy_sample', :as => :destroy_plate_sample, :via => :post
  match '/plates/:id/dup' => 'plates#dup', :as => :dup_plate, :via => :post

  get 'sample_show' => 'samples#show'
  get 'sample_log'  => 'samples#show_log'
  get 'sample_edit' => 'samples#edit'
  post 'sample_receive_by_crc_id' => 'samples#receive_by_crc_id'
  match '/samples/receive' => 'samples#receive', :as => :receive_sample
  match '/samples/receive_multiple/:url_codes' => 'samples#receive_multiple', :as => :receive_multiple_samples
  match '/samples/receive_multiple_confirm' => 'samples#receive_multiple_confirm', :as => :receive_multiple_samples_confirm, :via => :post
  match '/samples/:id/log' => 'samples#show_log', :as => :show_sample_log, :via => :get
  match '/samples/:id/participant_note' => 'samples#participant_note', :as => :sample_participant_note, :via => :get
  match '/samples/:id/participant_note' => 'samples#update_participant_note', :as => :sample_update_participant_note, :via => :put
  match '/samples/:id/destroyed' => 'samples#mark_as_destroyed', :as => :sample_destroyed, :via => :post
  resources :samples
  match '/samples/:id/received' => 'samples#received', :as => :received_sample, :via => :post
  match '/samples/m/:url_code/undo_reception' => 'samples#mobile_undo_reception', :as => :mobile_sample_undo_reception, :via => :get
  match '/samples/m/:url_code/receive' => 'samples#mobile_receive', :as => :mobile_sample_receive, :via => :get
  match '/samples/m/:url_code' => 'samples#mobile', :as => :mobile_sample, :via => :get
  resources :specimens, :controller => "samples"

  resources :unused_kit_names

  match '/kits/:id/log' => 'kits#show_log', :as => :show_kit_log, :via => :get
  match '/kits/:id/confirm_claim' => 'kits#confirm_claim', :as => :kit_confirm_claim, :via => :post
  match '/kits/claim' => 'kits#claim', :as => :kit_claim

  match '/admin/researchers/study_filter_results' => 'admin/researchers#study_filter_results', :format => 'csv', :as => :study_filter_results_csv

  resources :kits
  match '/kits/:id/sent' => 'kits#sent', :as => :sent_kit, :via => :post
  match '/kits/:id/returned' => 'kits#returned', :as => :returned_kit, :via => :post
  match '/kits/sent_selected' => 'kits#sent_selected', :as => :sent_selected_kits, :via => :post
  match '/kits/:id/lost' => 'kits#lost', :as => :lost_kit, :via => :post

  resources :traitwise_surveys do
    post 'participate', :on => :member
    post 'synchronize', :on => :member
    post 'download', :on => :member
  end
  match '/traitwise/proxy' => 'traitwise#proxy'
  match '/traitwise/:id' => 'traitwise#index', :as => :take_traitwise_survey
  match '/traitwise/:id/iframe' => 'traitwise#iframe', :as => :traitwise_iframe

  resources :google_surveys do
    post 'participate', :on => :member
    # So that going via login_required when clicking on the link in a reminder e-mail doesn't break the flow,
    # we also support the GET method.
    get 'participate', :on => :member
    post 'synchronize', :on => :member
    post 'send_test_reminder', :on => :member
    match 'download', :on => :member
    match 'download_bypasses', :on => :member
  end
  match '/nonce/:id' => 'nonces#delete', :as => :delete_google_survey_answers, :via => :delete
  match '/google_survey_reminder/edit' => 'google_survey_reminders#edit', :as => :edit_google_survey_reminder
  match '/google_survey_reminder/update' => 'google_survey_reminders#update', :as => :update_google_survey_reminder, :via => :post
  # So that going via login_required when clicking on the link in a reminder e-mail doesn't break the flow,
  # we also support the GET method.
  match '/google_survey_bypass/:token' => 'google_survey_bypasses#record', :as => :google_survey_bypass, :via => [:get, :post]

  resources :google_spreadsheets do
    post 'synchronize', :on => :member
  end

  get "oauth_tokens/authorize"
  get "oauth_tokens/revoke"
  match "oauth_tokens/get_access_token" => 'oauth_tokens#get_access_token', :as => :get_oauth_access_token, :via => :get
  get 'oauth2callback' => 'oauth_tokens#oauth2callback', :as => :oauth2callback
  resources :oauth_tokens, :only => :index

  resources :kit_design_samples
  get 'sample_type_show' => 'sample_types#show'
  resources :sample_types
  resources :units
  resources :device_types
  resources :tissue_types
  resources :kit_designs
  match '/collection_events/claim' => 'studies#claim', :as => :study_claim_kit
  match '/collection_events/:id/users' => 'studies#users', :as => :study_users
  match '/collection_events/:id/sent_kits_to_selected' => 'studies#sent_kits_to_selected', :as => :sent_kits_to_selected_study_users
  match '/collection_events/:id/map' => 'studies#map', :as => :study_map
  match '/collection_events/:study_id/users/:user_id/:status' => 'studies#update_user_status', :as => :study_update_user_status
  match '/collection_events/:id/sent_kits_to_selected' => 'studies#sent_kits_to_selected', :as => :sent_kits_to_selected_study_users, :via => :post
  match '/collection_events/:id/accept_interested_selected' => 'studies#accept_interested_selected', :as => :accept_interested_selected_study_users, :via => :post
  resources :collection_events, :controller => "studies"
  match '/pages/studies', :to => redirect('/pages/collection_events')
  match '/studies/*x', :to => redirect('/collection_events/%{x}')

  get 'third_party/index'
  get 'third_party/study/:id' => 'studies#show_third_party', :as => :third_party_study
  match '/third_party/study/:id/verify_participant_id/:app_token' => 'studies#verify_participant_id', :via => [:get], :as => :verify_third_party_participant_id
  match '/third_party/study/:id/clickthrough_to' => 'studies#clickthrough_to', :via => [:post], :as => :clickthrough_to_third_party
  post '/third_party/add_dataset' => 'studies#add_dataset'
  match '/3p/*x', :to => redirect('/third_party/%{x}')

  get 'open_humans/participate'
  post 'open_humans/disconnect'
  post 'open_humans/tokens', :to => 'open_humans#create_token'
  post 'open_humans/huids', :to => 'open_humans#create_huid'
  get 'open_humans/huids'
  # This callback URL is set on the Open Humans API server
  get 'auth/open-humans/callback' => 'open_humans#callback'

  match '/filters/upload' => 'filters#upload', :as => :upload_filter, :via => :post

  resources :pages
  match '/23andme' => 'pages#show', :id => '23andme', :as => 'twenty3andme'
  match '/23andMe' => 'pages#show', :id => '23andme', :as => 'twenty3andme'
  match '/enrolled', :to => redirect('/users')
  match '/users/initial' => 'users#initial', :as => :initial_user
  match '/users/create_initial' => 'users#create_initial', :as => :create_initial_user
  match '/users/new2' => 'users#new2', :as => :new2_user
  match '/users/accept_enrollment' => 'users#accept_enrollment', :as => :accept_enrollment_user
  match '/users/tos' => 'users#tos', :as => :tos_user
  match '/users/accept_tos' => 'users#accept_tos', :as => :accept_tos_user
  match '/users/consent' => 'users#consent', :as => :consent_user
  match '/users/unauthorized' => 'users#unauthorized', :as => :unauthorized_user
  match '/users/deactivated' => 'users#deactivated', :as => :deactivated_user
  match '/users/created/:id' => 'users#created', :as => :created_user
  match '/users/show_log' => 'users#show_log', :as => :show_log_user
  match '/users/withdraw' => 'users#withdraw', :as => :withdraw_user, :via => :post
  match '/users/withdraw_confirm' => 'users#withdraw_confirm', :as => :withdraw_confirm_user, :via => :post
  match '/users/:switch_to_id/switch_to' => 'users#switch_to', :via => [:post], :as => :switch_to_user
  match '/drb/userlog/:user_id' => 'drb#userlog', :as => :userlog_drb
  match '/user/study/:study_id' => 'users#edit_study', :as => :user_edit_study, :via => :get
  match '/user/study/:study_id' => 'users#update_study', :as => :user_update_study, :via => :post
  match '/users/resend_signup_notification_form' => 'users#resend_signup_notification_form', :as => :resend_signup_notification_form
  match '/users/resend_signup_notification/:id' => 'users#resend_signup_notification', :as => :resend_signup_notification_user
  match '/users/create_researcher', :as => :create_researcher, :via => :post
  match '/users/participant_survey' => 'users#participant_survey'
  resources :shipping_addresses
  match '/user/shipping_address' => 'users#shipping_address', :as => 'user_shipping_address'
  match '/user/edit' => 'users#edit', :as => 'edit_user', :method => :get
  match '/user/update' => 'users#update', :as => 'update_user', :method => :post
  resources :users

  resource :session
  match '/login' => 'sessions#new', :as => :login

app/models/traitwise_survey.rb
class TraitwiseSurvey < ActiveRecord::Base
  stampable
  acts_as_paranoid_versioned :version_column => :lock_version

  require 'uri'

  belongs_to :user
  has_one :spreadsheet_importer
  has_one :spreadsheet, :through => :spreadsheet_importer

  attr_protected :user_id
  attr_protected :spreadsheet_id

  CACHE_DIR = "/data/" + ROOT_URL + "/traitwise_surveys"

end

app/controllers/traitwise_surveys_controller.rb
class TraitwiseSurveysController < ApplicationController
  before_filter :ensure_researcher, :except => [:participate, :show, :index, :download]
  skip_before_filter :ensure_enrolled, :except => [:participate]

  def participate
    get_object
    if !@traitwise_survey.open
      flash[:error] = "This survey is not open for participation now."
      return redirect_to traitwise_survey_path(@traitwise_survey)
    end
    current_user.log("Clicked through to TraitwiseSurvey #{@traitwise_survey.id} (#{@traitwise_survey.name})", nil, request.remote_ip, "Clicked through to survey: #{@traitwise_survey.name}")
    redirect_to take_traitwise_survey_path(@traitwise_survey)
  end

  def decide_view_mode
    @can_edit = current_user.is_admin? or (@traitwise_survey and @traitwise_survey.user_id == current_user.id)
    @min_view = !@can_edit and !current_user.is_researcher?
    @can_download = (@traitwise_survey and
                     @sit.spreadsheet.last_downloaded_at and
                     (@traitwise_survey.is_result_public or
                      @traitwise_survey.user_id == current_user.id or
                      current_user.is_admin?))
  end

  def synchronize
    get_object
    decide_view_mode
    ok, error_message = @sit.synchronize!(current_user,request,cookies)
    if ok
      flash[:notice] = 'Results synchronized at ' + @sit.spreadsheet.last_downloaded_at.to_s
    else
      flash[:error] = error_message
    end
    redirect_to traitwise_survey_path(@traitwise_survey)
  end

  def download
    get_object
    decide_view_mode
    return access_denied unless @can_download

    filename = @traitwise_survey.name.gsub(' ','_').camelcase + '-' + @sit.spreadsheet.last_downloaded_at.strftime('%Y%m%d%H%M%S') + '.csv'

    @csv = CSV.generate_line(@sit.spreadsheet.header_row) + "\n"
    @sit.spreadsheet.spreadsheet_rows.each do |r|
      @csv += CSV.generate_line(r.row_data) + "\n"
    end

    send_data(@csv,
              :filename => filename,
              :disposition => 'attachment',
              :type => 'text/csv')
  end

  # GET /traitwise_surveys
  # GET /traitwise_surveys.xml
  def index
    decide_view_mode
    if @min_view
      @traitwise_surveys = TraitwiseSurvey.where(:is_listed => true)
    else
      @traitwise_surveys = TraitwiseSurvey.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @traitwise_surveys }
    end
  end

  # GET /traitwise_surveys/1
  # GET /traitwise_surveys/1.xml
  def show
    get_object
    decide_view_mode

    @nonces = Nonce.where(:owner_class => 'User', :owner_id => current_user.id,
                          :target_class => 'TraitwiseSurvey', :target_id => @traitwise_survey.id)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @traitwise_survey }
    end
  end

  # GET /traitwise_surveys/new
  # GET /traitwise_surveys/new.xml
  def new
    @traitwise_survey = TraitwiseSurvey.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @traitwise_survey }
    end
  end

  # GET /traitwise_surveys/1/edit
  def edit
    get_object
  end

  # POST /traitwise_surveys
  # POST /traitwise_surveys.xml
  def create
    @traitwise_survey = TraitwiseSurvey.new(params[:traitwise_survey])
    @traitwise_survey.user_id = current_user.id

    respond_to do |format|
      if @traitwise_survey.save
        s = Spreadsheet.new(:name => "Auto-generated spreadsheet for Traitwise survey results")
        sit = SpreadsheetImporterTraitwise.new(:traitwise_survey => @traitwise_survey)
        sit.save
        s.spreadsheet_importer = sit
        s.save
        @traitwise_survey.spreadsheet = s
        @traitwise_survey.save
        format.html { redirect_to(@traitwise_survey, :notice => 'Traitwise survey was successfully created.') }
        format.xml  { render :xml => @traitwise_survey, :status => :created, :location => @traitwise_survey }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @traitwise_survey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /traitwise_surveys/1
  # PUT /traitwise_surveys/1.xml
  def update
    get_object

    respond_to do |format|
      if @traitwise_survey.update_attributes(params[:traitwise_survey])
        format.html { redirect_to(@traitwise_survey, :notice => 'Traitwise survey was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @traitwise_survey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /traitwise_surveys/1
  # DELETE /traitwise_surveys/1.xml
  def destroy
    get_object
    @traitwise_survey.destroy

    respond_to do |format|
      format.html { redirect_to(traitwise_surveys_url) }
      format.xml  { head :ok }
    end
  end

private

  def get_object
    @traitwise_survey = TraitwiseSurvey.find(params[:id]) if params[:id] and !@traitwise_survey
    @sit = SpreadsheetImporterTraitwise.where('traitwise_survey_id = ?',@traitwise_survey.id).first
  end

end

app/views/traitwise_surveys/_form.html.erb
<%= form_for(@traitwise_survey) do |f| %>
  <div class="field">
    <%= f.label :name, 'Survey Name' %><br />
    <%= f.text_field(:name, :size => 40) %>
  </div>
  <div class="field">
    <%= f.label :open, 'Open?' %> (i.e., participants can respond click the "participate in this survey" button)<br />
    <%= f.check_box :open, :checked_value => true, :unchecked_value => false %>
  </div>
  <div class="field">
    <%= f.label :is_listed, 'Listed?' %> (in "available surveys" lists shown to participants)<br />
    <%= f.check_box :is_listed, :checked_value => true, :unchecked_value => false %>
  </div>
  <div class="field">
    <%= f.label :is_result_public, 'Results public?' %> (i.e., displayed on participants' public profiles, and downloadable as CSV by participants)<br />
    <%= f.check_box :is_result_public, :checked_value => true, :unchecked_value => false %>
  </div>
  <div class="field">
    <%= f.label :description, 'Description' %><br />
    <%= f.text_area :description, :cols => 80, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label(:tags, 'Traitwise tag') %><br />
    <%= f.text_field(:tags, :size => 80) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traitwise_surveys/edit.html.erb
<h2><%= link_to 'Traitwise surveys', traitwise_surveys_path %> &gt; Edit</h2>

<%= render 'form' %>

<%= link_to 'Back', traitwise_surveys_path %>

app/views/traitwise_surveys/index.html.erb
<%= button_to 'New Traitwise survey', new_traitwise_survey_path, :class => 'btn btn-primary pull-right', :method => :get unless @min_view %>

<h2>Traitwise surveys</h2>

<table class="admin_table">
  <tr>
    <th>Survey name</th>
    <th>Researcher</th>
    <th>Tag</th>
    <th>Results downloaded</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @traitwise_surveys.each do |traitwise_survey| %>
  <tr>
    <td><%= traitwise_survey.name %></td>
    <td><%= traitwise_survey.user.full_name if traitwise_survey.user %></td>
    <td><%= traitwise_survey.tags %></td>
    <td><%= SpreadsheetImporterTraitwise.where('traitwise_survey_id = ?', traitwise_survey.id).first.spreadsheet.last_downloaded_at %></td>
    <td><%= link_to 'Show', traitwise_survey %></td>
    <td><%= link_to 'Edit', edit_traitwise_survey_path(traitwise_survey) if current_user.is_admin? or current_user.id == traitwise_survey.user_id %></td>
    <td><%= button_to 'Destroy', traitwise_survey, :confirm => 'Are you sure?', :method => :delete if current_user.is_admin? or current_user.id == traitwise_survey.user_id %></td>
  </tr>
<% end %>
</table>

app/views/traitwise_surveys/new.html.erb
<h2><%= link_to 'Traitwise surveys', traitwise_surveys_path %> &gt; New</h2>

<%= render 'form' %>

app/views/traitwise_surveys/show.html.erb
<h2><% unless @min_view %><%= link_to 'Traitwise surveys', traitwise_surveys_path %> &gt; <% end %><%=h @traitwise_survey.name %></h2>

<p id="notice"><%= notice %></p>

<% if @traitwise_survey.user %>
<p>
  <b>Researcher:</b>
  <%=h @traitwise_survey.user.full_name %>,
  <%=h @traitwise_survey.user.researcher_affiliation %>
</p>
<% end %>

<p><%=raw CGI.escapeHTML(@traitwise_survey.description).gsub("\r","").gsub("\n\n","</p><p>") %></p>

<% if @can_edit or (current_user.enrolled and @traitwise_survey.open) %>
<p>
  <%= button_to 'Participate in this survey', participate_traitwise_survey_path(@traitwise_survey) %>
</p>
<% end %>
<% if !@traitwise_survey.open %>
<p>
  This survey is currently <%=raw '<b>not</b>' unless @traitwise_survey.open %> open to participants.
</p>
<% end %>

<% if @can_download %>
<p>
  <%= button_to 'Download results', download_traitwise_survey_path(@traitwise_survey) %>
</p>
<% end %>

<% if !@traitwise_survey.is_result_public %>
<p>
  Currently, responses to this survey are <b>not</b> publicly available.
</p>
<% end %>


<h3>Your participation in this survey</h3>
<% if !@nonces.empty? %>
<table class="admin_table">
  <thead>
    <th>Started taking survey</th>
    <th>Completed survey</th>
    <th>Results retrieved</th>
  </thead>
  <tbody>
    <% @nonces.each do |nonce| %>
    <tr>
      <td><%= nonce.created_at.localtime.ctime %></td>
      <td><%= a=TraitwiseSurveyAnswer.where(:traitwise_survey_id => @traitwise_survey.id, :nonce_id => nonce.id, :column => 1); (t=Time.parse(a[0].answer)) and t.ctime if a and a.size==1 and a[0].answer %></td>
      <td><%= nonce.used_at.localtime.ctime if nonce.used_at %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<p>You have not participated in this survey.</p>
<% end %>


<% if !@min_view %>
<h3>Technical details (this section is only displayed to researchers and admins)</h3>

<p>
  <b>Listed in "available surveys"?</b>
  <%= @traitwise_survey.is_listed ? "Yes" : "No" %>
</p>

<p>
  <b>Responses available to public?</b>
  <%= @traitwise_survey.is_result_public ? "Yes" : "No" %>
</p>

<p>
  <b>Results last synchronized:</b>
  <%=h @sit.spreadsheet.last_downloaded_at %>
</p>

<p>
  <b>Tag:</b>
  <%=h @traitwise_survey.tags %>
</p>

<% if @can_edit %>
<p>
  <%= button_to 'Synchronize results from Traitwise now', synchronize_traitwise_survey_path(@traitwise_survey) %>
</p>

<%= link_to 'Edit', edit_traitwise_survey_path(@traitwise_survey) %>
<% end %>
<% end %>